name: Pipeline steps.

on:
  push:
    branches: [master, main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Golangci Lint
        uses: golangci/golangci-lint-action@v2.5.2

      - name: Test
        run: go test -v ./...
